# -*- coding: utf-8 -*-
"""Descriptive stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iFWhNBZFLd2ql6WCHq_2DVtGv5jzHGrK
"""

import pandas as pd
import numpy as np
df=pd.read_csv('iris_dataset.csv')

df.sepal_length

df.sepal_length[0]

########################### Mean of Sepal_Length################# 
s=0
mean=0
for i in range(150):
  s=s+df.sepal_length[i]
mean=s/150
print(mean)

v=df[df['species']=='virginica']
v

n=df.sepal_length.count()
print(n)

################ Median ##############################33
n=df.sepal_length.count()
lst=[]
for i in range(n):
  lst.append(df.sepal_length[i])
lst.sort()
#print(lst)

b=n//2
med=0
if n%2==0:
  med=(lst[b]+lst[b+1])/2
else:
  med=lst[b]
print(med)

############################### MODE ############
import math as m
mode=3*med-2*mean
mode=m.floor(mode)
print(mode)

########################variance########################

s=0
mean=0
var=0
for i in range(150):
  s=s+(df.sepal_length[i]-mean)**2

var=s/df.sepal_length.count()
print(var)

############################ standard deviation ################
import math as m
sd=m.sqrt(var)
print(sd)

##############################3quartile ##################################
q1=df.sepal_length.count()//4
lq=df.sepal_length[q1]                      ##Lower Quartile

q3=3*q1
uq=df.sepal_length[q3]                            ##Upper Quartile

print("the lower quartile is:  ",lq)
print("the upper quartile is:  ",uq)
print("the IQR is: ",uq-lq)                            ##Inter quartile

############################### Skewness   #########################3
sk=(mean-mode)/sd
print(sk)

########################Kurtosis#############################

s=0
mean=0
v=0
for i in range(150):
  s=s+(df.sepal_length[i]-mean)

v=s/df.sepal_length.count()
kur=v/sd**4
print(kur)

######################################3CV############################3
mean=5.84
cv=sd/mean
print(cv)

