# -*- coding: utf-8 -*-
"""Copy of PandasNumpyMatplotlib.ynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RzJgJ12mn17L4MvQW3ZCiu-ghFeDSKt8
"""

import pandas as pd

dict1={'name':['Harshit Jain','Ali Bhaiya','Pramit']
       ,'marks':[49,47,42],'city':['Kolkata','Indore','Kolkata']
       }

df=pd.DataFrame(dict1)
df

df.to_csv('jain.csv')

df.to_csv('frnds.csv',index=False)

df.head(2)

df.describe()

hjain=pd.read_csv('jain.csv')
hjain

hjain['name']

hjain.index=['a','b','c']
hjain

from sklearn import datasets

iris=datasets.load_iris()
#print(iris.DESCR)

#df1=pd.DataFrame(iris)

from google.colab import drive
from google.colab import files
files.upload()
drive.mount('/content/drive')
file=open('/content/drive/My Drive/Colab Notebooks/iris_dataset.csv',"r")

import pandas as pd

import seaborn as sns

jain=pd.read_csv('iris_dataset.csv')
sns.pairplot(jain)

print(jain)

jain.head(5)

jain.sepal_length

jain.sepal_length.mean()

jain.describe()

jain.info()

jain['sepal_length'][0]=5.1

jain.head(5)

jain.tail(5)

jain.sepal_length.plot.kde()

jain.sepal_length

jain.loc[2]

jain.head(5)

jain.loc[2]['sepal_length']

df.iloc[0,5]

df.iloc[0:5,0:2]

jain.iloc[0:5,0:2]

df.head(5)

jain.head(5)

df.iloc[:,3]

jain[:,3]

jain.sepal_length.plot()

df.corr()

jain.corr()

jain.sepal_length.scatter_plot()

jain.sepal_length.plot()

jain.sepal_length.plot.pie()

import matplotlib.pyplot as plt
plt.scatter('sepal_length','sepal_width',data=jain)
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.title('iris')

jain.sepal_width.plot.kde()

virginica=jain[jain['species']=='virginica']
setosa=jain[jain['species']=='setosa']
virginica

jain['sepal_length']

jain[jain.sepal_length>5]

x=[1,2,3,4,5]
y=[6,7,8,9,10]
plt.subplot(2,2,1)
plt.plot(x,y)
plt.subplot(2,2,2)
plt.plot(y,x)
plt.subplot(2,2,3)
plt.plot(y,x)

plt.show()

import seaborn as sns
sns.pairplot()

jain['sepal_length']

jain.sepal_length

